version: '3.8'

services:
  spending-app:
    image: "spending-bot"
    container_name: "spending-bot"
    build:
      context: ./
      dockerfile: dockerfile
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"

  db:
    image: postgres:14.5
    restart: always
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
      #- ./migrations:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB="postgres"
      - POSTGRES_USER="postgres"
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G